project/: unsorted.c parity.c unique.c bincount.c set.h

	gcc -o parity parity.c unsorted.c
	gcc -o unique unique.c unsorted.c
	gcc -o bincount bincount.c unsorted.c
	time ./unique /scratch/coen12/Genesis.txt
	time ./unique /scratch/coen12/Genesis.txt
	time ./unique /scratch/coen12/Genesis.txt
	
	time ./unique /scratch/coen12/Macbeth.txt
	time ./unique /scratch/coen12/Macbeth.txt
	time ./unique /scratch/coen12/Macbeth.txt

	time ./unique /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./unique /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./unique /scratch/coen12/HoundOfTheBaskervilles.txt

	time ./unique /scratch/coen12/TheWarOfTheWorlds.txt
	time ./unique /scratch/coen12/TheWarOfTheWorlds.txt
	time ./unique /scratch/coen12/TheWarOfTheWorlds.txt

	time ./unique /scratch/coen12/TreasureIsland.txt
	time ./unique /scratch/coen12/TreasureIsland.txt
	time ./unique /scratch/coen12/TreasureIsland.txt

	time ./unique /scratch/coen12/TheSecretGarden.txt
	time ./unique /scratch/coen12/TheSecretGarden.txt
	time ./unique /scratch/coen12/TheSecretGarden.txt

	time ./unique /scratch/coen12/TheCountOfMonteCristo.txt
	time ./unique /scratch/coen12/TheCountOfMonteCristo.txt
	time ./unique /scratch/coen12/TheCountOfMonteCristo.txt

	time ./unique /scratch/coen12/TwentyThousandLeagues.txt
	time ./unique /scratch/coen12/TwentyThousandLeagues.txt
	time ./unique /scratch/coen12/TwentyThousandLeagues.txt

	time ./unique /scratch/coen12/Bible.txt
	time ./unique /scratch/coen12/Bible.txt
	time ./unique /scratch/coen12/Bible.txt

	time ./bincount /scratch/coen12/Genesis.txt
	time ./bincount /scratch/coen12/Genesis.txt
	time ./bincount /scratch/coen12/Genesis.txt

	time ./bincount /scratch/coen12/Macbeth.txt
	time ./bincount /scratch/coen12/Macbeth.txt
	time ./bincount /scratch/coen12/Macbeth.txt

	time ./bincount /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./bincount /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./bincount /scratch/coen12/HoundOfTheBaskervilles.txt

	time ./bincount /scratch/coen12/TheWarOfTheWorlds.txt
	time ./bincount /scratch/coen12/TheWarOfTheWorlds.txt
	time ./bincount /scratch/coen12/TheWarOfTheWorlds.txt

	time ./bincount /scratch/coen12/TreasureIsland.txt
	time ./bincount /scratch/coen12/TreasureIsland.txt
	time ./bincount /scratch/coen12/TreasureIsland.txt

	time ./bincount /scratch/coen12/TheSecretGarden.txt
	time ./bincount /scratch/coen12/TheSecretGarden.txt
	time ./bincount /scratch/coen12/TheSecretGarden.txt

	time ./bincount /scratch/coen12/TheCountOfMonteCristo.txt
	time ./bincount /scratch/coen12/TheCountOfMonteCristo.txt
	time ./bincount /scratch/coen12/TheCountOfMonteCristo.txt

	time ./bincount /scratch/coen12/TwentyThousandLeagues.txt
	time ./bincount /scratch/coen12/TwentyThousandLeagues.txt
	time ./bincount /scratch/coen12/TwentyThousandLeagues.txt

	time ./bincount /scratch/coen12/Bible.txt
	time ./bincount /scratch/coen12/Bible.txt
	time ./bincount /scratch/coen12/Bible.txt

	time ./parity /scratch/coen12/Genesis.txt
	time ./parity /scratch/coen12/Genesis.txt
	time ./parity /scratch/coen12/Genesis.txt

	time ./parity /scratch/coen12/Macbeth.txt
	time ./parity /scratch/coen12/Macbeth.txt
	time ./parity /scratch/coen12/Macbeth.txt

	time ./parity /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./parity /scratch/coen12/HoundOfTheBaskervilles.txt
	time ./parity /scratch/coen12/HoundOfTheBaskervilles.txt

	time ./parity /scratch/coen12/TheWarOfTheWorlds.txt
	time ./parity /scratch/coen12/TheWarOfTheWorlds.txt
	time ./parity /scratch/coen12/TheWarOfTheWorlds.txt

	time ./parity /scratch/coen12/TreasureIsland.txt
	time ./parity /scratch/coen12/TreasureIsland.txt
	time ./parity /scratch/coen12/TreasureIsland.txt

	time ./parity /scratch/coen12/TheSecretGarden.txt
	time ./parity /scratch/coen12/TheSecretGarden.txt
	time ./parity /scratch/coen12/TheSecretGarden.txt

	time ./parity /scratch/coen12/TheCountOfMonteCristo.txt
	time ./parity /scratch/coen12/TheCountOfMonteCristo.txt
	time ./parity /scratch/coen12/TheCountOfMonteCristo.txt

	time ./parity /scratch/coen12/TwentyThousandLeagues.txt
	time ./parity /scratch/coen12/TwentyThousandLeagues.txt
	time ./parity /scratch/coen12/TwentyThousandLeagues.txt

	time ./parity /scratch/coen12/Bible.txt
	time ./parity /scratch/coen12/Bible.txt
	time ./parity /scratch/coen12/Bible.txt



